version: '3.8'

services:
  torchlit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/torchlit/frontend/node_modules
      - /app/torchlit/frontend/dist
    ports:
      - "8000:8000"
    tty: true # Required for Rust TUI to render
    stdin_open: true # Required for interactive terminal output
